### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by pietro909** [peteruithoven/systemjs-debugger#4]
Hi there,
I'm trying to use your tool, but as of now is not in the npm registry: do you have any plan to publish it?

Thanks,
Pietro

**Comment by ineentho** [comment]
Even tough I too would prefer a npm release, it's possible to use directly from github (that's in fact how jspm suggests doing it). If you are using jspm:

`jspm i github:peteruithoven/systemjs-debugger`

**Comment by peteruithoven** [comment]
I did actually add it to JSPM's registry, so you could even simply do:
jspm install systemjs-debugger

I guess I should clarify this in the readme.

For publication on npm I would appreciate pull requests.

**Comment by pietro909** [comment]
> For publication on npm I would appreciate pull requests.

That's it, I can look into this one: I really like the debug tool, and in my company's pipeline there's no `jspm`.

Thanks!

**Comment by ineentho** [comment]
npm too has support for github, perhaps `npm i -S github:peteruithoven/systemjs-debugger` could work?

**Comment by pietro909** [comment]
I'm currently getting an error with that command:

```
npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\pigr2\AppData\Roaming\npm-cache\_git-remotes\git-github-com-peteruithoven-systemjs-debugger-git-6023de3e C:\cygwin64\tmp\npm-11744-a9bec90a\git-cache-287589ca\aa7057673b8a642a30550e699857538b021a6f9a
npm ERR! Cloning into 'C:\cygwin64\tmp\npm-11744-a9bec90a\git-cache-287589ca\aa7057673b8a642a30550e699857538b021a6f9a'...
npm ERR! fatal: '/cygdrive/c/Users/pigr2/AppData/Roaming/npm-cache/_git-remotes/git-github-com-peteruithoven-systemjs-debugger-git-6023de3e/C:\Users\pigr2\AppData\Roaming\npm-cache\_git-remotes\git-github-com-peteruithoven-systemjs-debugger-git-6023de3e' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
```

**Comment by ineentho** [comment]
Looks like some cygwin issue, right? Mixed C:/ and /cygwin/ paths. Maybe it would be easier to publish it to npm :)

**Comment by pietro909** [comment]
Yes, unfortunately, I have windows at work :(
I should be fast to publish it, there's no name conflict with other packages and the `package.json` is ready. No need for PR, if not an update to the Readme.

@peteruithoven I'd really appreciate if you could publish it 👍

**Comment by peteruithoven** [comment]
Alright, I was assuming this required more work. I fixed the version in package.json and published. Please let us know if it works like this.

**Comment by eppsilon** [comment]
Installing it from NPM worked fine for me.

**Comment by peteruithoven** [comment]
Thanks for the confirmation!
